# Generated by Django 2.2.10 on 2020-02-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsvFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WaveText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('before_normalization', models.CharField(max_length=300)),
                ('after_normalization', models.CharField(max_length=300)),
                ('modified', models.BooleanField(default=False)),
            ],
        ),
    ]
