# Generated by Django 2.2.10 on 2020-02-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_corrector', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvfile',
            options={'verbose_name_plural': 'Pliki CSV'},
        ),
        migrations.AlterModelOptions(
            name='wavetext',
            options={'verbose_name_plural': 'Teksty w plikach wave'},
        ),
        migrations.AlterField(
            model_name='wavetext',
            name='before_normalization',
            field=models.TextField(max_length=300),
        ),
    ]
